cask_args appdir: "/Applications"

tap "homebrew/cask"

brew "zsh"
brew "git"
brew "svn"
brew "htop"
brew "jq"
brew "nmap"
brew "tree"
brew "watch"
brew "wget"
brew "yq"
cask "google-cloud-sdk"
cask "firefox"
brew "go"
brew "kubernetes-cli"
brew "kubebuilder"
brew "kind"
brew "kustomize"
brew "pinentry-mac"
brew "gnupg"
cask "gpg-suite"
cask "zoom"
cask "notion"
cask "slack"
cask "google-chrome"
brew "podman"
brew "gron"
brew "neovim"
cask "goland"
cask "alacritty"
cask "1password"
cask "microsoft-teams"
brew "defaultbrowser"

tap "homebrew/cask-fonts"
cask "font-source-code-pro"

