# Custom local machine or secret envars
localzshenv=~/.zshenv.local
if [ -f "${localzshenv}" ]
then
    source "${localzshenv}"
fi

# GPG Agent
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

# Go
if command -v go &> /dev/null
then
  export GOPATH="$(go env GOPATH)"
  export PATH="$PATH:${GOPATH}/bin"
fi

# Rust
if [ -d "$HOME/.cargo/bin" ]
then
  export PATH="$PATH:$HOME/.cargo/bin"
fi

export LANG=en_GB.UTF-8
export EDITOR=vim
