# Custom local machine or secret envars
localzshenv=~/.zshenv.local
if [ -f "${localzshenv}" ]
then
    source "${localzshenv}"
fi

if command -v go &> /dev/null
then
   export GOPATH="$(go env GOPATH)"
   export PATH="$PATH:${GOPATH}/bin"
fi

export LANG=en_GB.UTF-8
export EDITOR=vim
