# Oh My ZSH configuration
export ZSH=~/.oh-my-zsh
ZSH_THEME="bernkastel"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
export ZSH_CUSTOM=~/.zsh-custom

# GPG Agent
GPG_TTY=$(tty)
export GPG_TTY

unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

# Oh My ZSH plugins
plugins=(git kubectl terraform colored-man-pages)

# Custom local machine or secret config
localzshrc=~/.zshrc.local
if [ -f "${localzshrc}" ]
then
    source "${localzshrc}"
fi

# Load Oh My ZSH
source $ZSH/oh-my-zsh.sh
